### ISSUE TITLE
[0.9.12] About 22 of TS errors like TS2304 and other

### ISSUE THREAD

**Issue by VictorYakushenko** [bootstrap-vue-next/bootstrap-vue-next#1221]
**Describe the bug.** A clear and concise description of what the bug is.

**To Reproduce.** Steps to reproduce the behavior:

1. Install bootstrap bootstrap-vue-next 0.9.12
2. npm run build

**Expected behavior.** Project is built

**Screenshots.** If applicable, add screenshots to help explain your problem.
![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/19596916/f330d0a8-a302-4314-a314-bc2170f6f6e7)

**Environment (please complete the following information):**

- OS: Windows 11
- Package Version: 0.9.12
- Npm 9.5.1

**Comment by VividLemon** [comment]
Receiving no such issue on my end. 

Delete and reinstall your node_modules & your package-lock and then create a reproduction if it continues.

**Comment by VictorYakushenko** [comment]
> Receiving no such issue on my end.
> 
> Delete and reinstall your node_modules & your package-lock and then create a reproduction if it continues.

Didn't help. Bug is reproduced for new vue ts projec
![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/19596916/f33c3f4c-fbd1-428e-89b7-bae58b7cfaf1)

**Comment by dpash** [comment]
I'm also seeing a number of issues from vue-tsc upgrading from 0.9.9 to 0.9.12

```
 Error: node_modules/bootstrap-vue-next/src/components/BTable/itemHelper.ts(11,19): error TS2769: No overload matches this call.
  Overload 1 of 2, '(o: {}): string[]', gave the following error.
    Argument of type 'TableItem | undefined' is not assignable to parameter of type '{}'.
      Type 'undefined' is not assignable to type '{}'.
  Overload 2 of 2, '(o: object): string[]', gave the following error.
    Argument of type 'TableItem | undefined' is not assignable to parameter of type 'object'.
      Type 'undefined' is not assignable to type 'object'.
Error: node_modules/bootstrap-vue-next/src/components/BTable/itemHelper.ts(50,17): error TS18048: 'flags.sortDescBoolean' is possibly 'undefined'.
Error: node_modules/bootstrap-vue-next/src/components/BToast/plugin.ts(85,31): error TS7030: Not all code paths return a value.
Error: node_modules/bootstrap-vue-next/src/components/BToast/plugin.ts(97,44): error TS7030: Not all code paths return a value.
Error: node_modules/bootstrap-vue-next/src/components/BToast/plugin.ts(154,9): error TS2322: Type 'ToastVM | undefined' is not assignable to type 'ToastVM'.
  Type 'undefined' is not assignable to type 'ToastVM'.
Error: node_modules/bootstrap-vue-next/src/components/BToast/plugin.ts(164,9): error TS2322: Type 'ToastVM | undefined' is not assignable to type 'ToastVM'.
  Type 'undefined' is not assignable to type 'ToastVM'.
Error: node_modules/bootstrap-vue-next/src/components/BFormFile/BFormFile.vue(136,82): error TS2488: Type 'FileList' must have a '[Symbol.iterator]()' method that returns an iterator.
Error: node_modules/bootstrap-vue-next/src/components/BFormSpinButton/BFormSpinButton.vue(364,24): error TS7030: Not all code paths return a value.
Error: node_modules/bootstrap-vue-next/src/components/BFormTags/BFormTag.vue(73,11): error TS2532: Object is possibly 'undefined'.
Error: node_modules/bootstrap-vue-next/src/components/BTabs/BTabs.vue(173,33): error TS2532: Object is possibly 'undefined'.
Error: node_modules/bootstrap-vue-next/src/components/BTabs/BTabs.vue(199,5): error TS2322: Type '{ buttonId: any; contentId: any; disabled: boolean; target: string; title: any; titleItemClass: any; titleLinkAttributes: any; onClick: any; tab: VNode<RendererNode, RendererElement, { ...; }>; tabComponent: () => VNode<...> | undefined; }[]' is not assignable to type '{ buttonId: string; contentId: string; disabled: boolean; target: string; title: string; titleItemClass: any; titleLinkAttributes: Record<string, unknown>; onClick: (e: Event) => void; tab: VNode<...>; tabComponent: () => VNode<...>; }[]'.
  Type '{ buttonId: any; contentId: any; disabled: boolean; target: string; title: any; titleItemClass: any; titleLinkAttributes: any; onClick: any; tab: VNode<RendererNode, RendererElement, { ...; }>; tabComponent: () => VNode<...> | undefined; }' is not assignable to type '{ buttonId: string; contentId: string; disabled: boolean; target: string; title: string; titleItemClass: any; titleLinkAttributes: Record<string, unknown>; onClick: (e: Event) => void; tab: VNode<...>; tabComponent: () => VNode<...>; }'.
    The types returned by 'tabComponent()' are incompatible between these types.
      Type 'VNode<RendererNode, RendererElement, { [key: string]: any; }> | undefined' is not assignable to type 'VNode<RendererNode, RendererElement, { [key: string]: any; }>'.
        Type 'undefined' is not assignable to type 'VNode<RendererNode, RendererElement, { [key: string]: any; }>'.
Error: node_modules/bootstrap-vue-next/src/components/BTabs/BTabs.vue(279,8): error TS2532: Object is possibly 'undefined'.
Error: node_modules/bootstrap-vue-next/src/components/BTabs/BTabs.vue(280,30): error TS2532: Object is possibly 'undefined'.
Error: node_modules/bootstrap-vue-next/src/components/BTabs/BTabs.vue(300,6): error TS2532: Object is possibly 'undefined'.
Error: node_modules/bootstrap-vue-next/src/components/BTabs/BTabs.vue(302,12): error TS2532: Object is possibly 'undefined'.
Error: node_modules/bootstrap-vue-next/src/components/BTabs/BTabs.vue(304,5): error TS2532: Object is possibly 'undefined'.
Error: node_modules/bootstrap-vue-next/src/components/BTabs/BTabs.vue(323,43): error TS2532: Object is possibly 'undefined'.
Error: node_modules/bootstrap-vue-next/src/components/BTabs/BTabs.vue(347,42): error TS2532: Object is possibly 'undefined'.
Error: node_modules/bootstrap-vue-next/src/composables/useFormSelect.ts(7,25): error TS2538: Type 'undefined' cannot be used as an index type.
Error: node_modules/bootstrap-vue-next/src/utils/classes/BvCarouselEvent.ts(24,14): error TS4114: This member must have an 'override' modifier because it overrides a member in the base class 'BvEvent'.
Error: node_modules/bootstrap-vue-next/src/utils/classes/BvTriggerableEvent.ts(17,14): error TS4114: This member must have an 'override' modifier because it overrides a member in the base class 'BvEvent'.
Error: node_modules/bootstrap-vue-next/src/utils/floatingUi.ts(42,7): error TS2322: Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.
Error: node_modules/bootstrap-vue-next/src/utils/locale.ts(28,60): error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.
Error: node_modules/bootstrap-vue-next/src/utils/normalizeSlot.ts(9,19): error TS2538: Type 'undefined' cannot be used as an index type.
Error: node_modules/bootstrap-vue-next/src/utils/sanitizer.ts(107,25): error TS2488: Type 'NodeListOf<Element>' must have a '[Symbol.iterator]()' method that returns an iterator.
Error: Process completed with exit code 2.
```

I don't know if you want me to create this as a separate issue

**Comment by dpash** [comment]
They're clearly an issue:

    Error: node_modules/bootstrap-vue-next/src/components/BToast/plugin.ts(85,31): error TS7030: Not all code paths return a value.

https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/4f8f4ea0454ee1bb65b8ba615ce171ca03cf6724/packages/bootstrap-vue-next/src/components/BToast/plugin.ts#L85

It correctly points out that not all code paths return a result.

```
       this.vm.toasts.filter((toast) => {
          if (toast.options.pos === position && toast.options.value) {
            return toast
          }
        })
```

**Comment by VividLemon** [comment]
> They're clearly an issue:

Since there's clearly an issue, and you clearly have a reproduction, you can clearly fix the issue yourself. Or would you prefer to do what I ask?

**Comment by dpash** [comment]
Create a project, install bootstrap-vue-next and enable the following tsconfig.json options:

```
    "allowUnreachableCode": false,
        "noImplicitOverride": true,
        "noImplicitReturns": true,
        "noUncheckedIndexedAccess": true,
```
Works with 0.9.10. Does not work with 0.9.12. The code that's throwing errors has not changed between versions, so I can only assume it's the change of `.d.ts` files from `dist/src` to `src`.

**Comment by VividLemon** [comment]
If there is no linked repository, I will simply close the issue.

**Comment by VictorYakushenko** [comment]
> If there is no linked repository, I will simply close the issue.

https://github.com/VictorYakushenko/bootstrap-vue-next-error

**Comment by dpash** [comment]
https://github.com/dpash/bootstrap-vue-next-error

  npm run vue-tsc

**Comment by VividLemon** [comment]
Should be fixed https://github.com/bootstrap-vue-next/bootstrap-vue-next/releases/tag/bootstrap-vue-next-v0.9.13

**Comment by VictorYakushenko** [comment]
> Should be fixed https://github.com/bootstrap-vue-next/bootstrap-vue-next/releases/tag/bootstrap-vue-next-v0.9.13

fixed

**Comment by dpash** [comment]
Can confirm fixed on my end too. Thanks.
